# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np



In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_d= np.array([2,34,5])

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[3,4,5],
                 [4,5,7]])

# Create a 3-dimensional Numpy array using np.array()
three_d = np.array([[[2,4,5],[5,7,8]],
                    [[5,9,1],[4,7,1]],
                    [[6,7,8],[9,2,4]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_d.ndim


1

In [4]:
one_d.dtype

dtype('int32')

In [5]:
one_d.shape

(3,)

In [6]:
one_d.size

3

In [7]:
type(one_d)

numpy.ndarray

In [8]:
# Attributes of 2-dimensional array
two_d.shape


(2, 3)

In [9]:
two_d.size

6

In [10]:
two_d.dtype

dtype('int32')

In [11]:
type(two_d)

numpy.ndarray

In [12]:
# Attributes of 3-dimensional array
three_d.shape

(3, 2, 3)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [14]:
two_d

array([[3, 4, 5],
       [4, 5, 7]])

In [15]:
panda_df= pd.DataFrame(two_d)
panda_df

0  1  2
0  3  4  5
1  4  5  7

In [16]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2),int)
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [17]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3),int)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
rang = np.arange(0,100,3)
rang

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randomArray = np.random.randint(0,10,size=(7,2),dtype =int)
randomArray

array([[7, 5],
       [0, 1],
       [1, 4],
       [2, 5],
       [7, 9],
       [1, 5],
       [4, 2]])

In [20]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
flt = np.random.random((3,5))
flt

array([[0.69343402, 0.64530963, 0.37452472, 0.0344573 , 0.06989855],
       [0.92944048, 0.47039841, 0.65820863, 0.5672368 , 0.63251463],
       [0.63857222, 0.10876315, 0.80798929, 0.49354463, 0.57195518]])

In [21]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
Seed_array=np.random.randint(0,10,size =(4,6))
Seed_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [22]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


# Find the unique numbers in the array you just created

random_array_1_10 = np.random.randint(1,10,size=(3,7))
random_array_1_10

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [23]:
np.unique(random_array_1_10,return_index=True)

(array([1, 2, 3, 4, 5, 7, 9]),
 array([ 1, 13,  2,  4,  7,  3,  0], dtype=int64))

In [24]:
# Find the 0'th index of the latest array you created
random_array_1_10[0][0]

9

In [25]:
# Get the first 2 rows of latest array you created
random_array_1_10[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [26]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_1_10[:2,:2]


array([[9, 1],
       [5, 3]])

In [27]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(3)
ran_again = np.random.randint(0,10,size =(3,5))
ran_again

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4]])

In [28]:
array_ons = np.ones((3,5))
array_ons

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Add the two arrays together
np.add(array_ons,ran_again)

array([[ 9., 10.,  4.,  9.,  9.],
       [ 1.,  6.,  4., 10., 10.],
       [ 6.,  8.,  7.,  1.,  5.]])

In [30]:
# Create another array of ones of shape (5, 3)
array_5_3= np.ones((5,3))
array_5_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# Try add the array of ones and the other most recent array together


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [32]:
mat_1= np.random.randint(10,size = (4,5))
mat_2= np.random.randint(10,size=(5,3))
np.dot(mat_1,mat_2)

array([[ 88, 103, 163],
       [ 94,  74,  79],
       [ 87, 100, 170],
       [ 41,  29,  77]])

In [39]:
# Create another array of ones of shape (3, 5) 
array35 = np.ones((3,5),int) 
array35

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:

array35.shape


(3, 5)

In [44]:
mat_2.view()

array([[4, 7, 6],
       [0, 0, 9],
       [2, 4, 5],
       [8, 8, 7],
       [5, 1, 1]])

In [43]:
np.reshape(mat_2,(3,5))

array([[4, 7, 6, 0, 0],
       [9, 2, 4, 5, 8],
       [8, 7, 5, 1, 1]])

In [45]:
# Subtract the new array of ones from the other most recent array
np.subtract(np.reshape(mat_2,(3,5)),array35)

array([[ 3,  6,  5, -1, -1],
       [ 8,  1,  3,  4,  7],
       [ 7,  6,  4,  0,  0]])

In [46]:
# Multiply the ones array with the latest array
mat_1,array35


(array([[7, 8, 1, 6, 2],
        [2, 1, 3, 5, 8],
        [1, 8, 7, 8, 1],
        [0, 5, 4, 1, 5]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [48]:
np.multiply(array35,np.reshape(mat_2,(3,5)))

array([[4, 7, 6, 0, 0],
       [9, 2, 4, 5, 8],
       [8, 7, 5, 1, 1]])

In [49]:
# Take the latest array to the power of 2 using '**'
mat_2**2

array([[16, 49, 36],
       [ 0,  0, 81],
       [ 4, 16, 25],
       [64, 64, 49],
       [25,  1,  1]], dtype=int32)

In [50]:
# Do the same thing with np.square()
np.square(mat_2)

array([[16, 49, 36],
       [ 0,  0, 81],
       [ 4, 16, 25],
       [64, 64, 49],
       [25,  1,  1]], dtype=int32)

In [51]:
# Find the mean of the latest array using np.mean()
np.mean(mat_2)


4.466666666666667

In [52]:
# Find the maximum of the latest array using np.max()
np.max(mat_2)

9

In [53]:
# Find the minimum of the latest array using np.min()
np.min(mat_2)

0

In [54]:
# Find the standard deviation of the latest array
np.std(mat_2)

2.963481436119049

In [55]:
# Find the variance of the latest array
np.var(mat_2)


8.782222222222222

In [56]:
# Reshape the latest array to (3, 5, 1)
mat_2.reshape(3,5,1)


array([[[4],
        [7],
        [6],
        [0],
        [0]],

       [[9],
        [2],
        [4],
        [5],
        [8]],

       [[8],
        [7],
        [5],
        [1],
        [1]]])

In [57]:
# Transpose the latest array
mat_2.T


array([[4, 0, 2, 8, 5],
       [7, 0, 4, 8, 1],
       [6, 9, 5, 7, 1]])

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [ ]:
# Perform a dot product on the two newest arrays you created


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [ ]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [59]:
# Compare the two arrays with '>'
array35>mat_2.reshape(3,5)


array([[False, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

What happens when you compare the arrays with `>`?

In [60]:
# Compare the two arrays with '>='
array35>mat_2.reshape(3,5)


array([[False, False, False,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [70]:
#butter sales dataframe
np.random.seed(0)
sales_amount = np.random.randint(1,100,size=(5,3))
sales_amount.view()

array([[45, 48, 65],
       [68, 68, 10],
       [84, 22, 37],
       [88, 71, 89],
       [89, 13, 59]])

In [71]:
import pandas as pd

In [80]:
#creat price array
prices = np.array([10,8,12])
prices,prices.shape

(array([10,  8, 12]), (3,))

In [81]:
#creat butter prices data frame
butter_prices= pd.DataFrame(prices,index=["Prices"],columns=["Almond butter","Peanut butter","Cashew butter"])

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [82]:
price.shape

(3,)

In [111]:
butter_prices= pd.DataFrame(prices.reshape(1,3),index=["Prices"],columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [112]:
weekly_sales = pd.DataFrame(sales_amount,index=["Mon","Tues","Wed","Thurs","fri"],columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               45             48             65
Tues              68             68             10
Wed               84             22             37
Thurs             88             71             89
fri               89             13             59

In [113]:
prices

array([10,  8, 12])

In [98]:
sales_amount


array([[45, 48, 65],
       [68, 68, 10],
       [84, 22, 37],
       [88, 71, 89],
       [89, 13, 59]])

In [114]:
totel_sales = np.dot(sales_amount,prices.T)
totel_sales

array([1614, 1344, 1460, 2516, 1702])

In [115]:
daily_sales= butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues   Wed  Thurs   fri
Prices  1614  1344  1460   2516  1702

In [118]:
weekly_sales["Totel"]=daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Totel
Mon               45             48             65   1614
Tues              68             68             10   1344
Wed               84             22             37   1460
Thurs             88             71             89   2516
fri               89             13             59   1702

In [108]:
#weekly_sales["Totel"]=totel_sales.T
#weekly_sales


In [ ]:
# Find which elements of the first array are greater than 7


In [ ]:
# Which parts of each array are equal? (try using '==')


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [ ]:
# Create an array of normally distributed random numbers


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.